<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/10/20 15:01:54
$this->security = array (
  'catalogues' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
