<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/10/20 15:01:54
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'password' => 
  array (
    'is_secure' => false,
  ),
  'resetpassword' => 
  array (
    'is_secure' => false,
  ),
  'activateuser' => 
  array (
    'is_secure' => false,
  ),
  'loginshowfolder' => 
  array (
    'is_secure' => false,
  ),
  'tokenconnect' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
