<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/10/20 15:01:53
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'setculture' => 
  array (
    'is_secure' => false,
  ),
  'redirect' => 
  array (
    'is_secure' => false,
  ),
  'payment' => 
  array (
    'is_secure' => false,
  ),
  'getindicatif' => 
  array (
    'is_secure' => false,
  ),
  'error' => 
  array (
    'is_secure' => false,
  ),
);
