<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/20 15:01:54
sfConfig::add(array(
  'mod_chcmsexposerouting_enabled' => true,
  'mod_chcmsexposerouting_view_class' => 'sfPHP',
));
