<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/10/20 15:01:54
$this->security = array (
  'replaceprocess' => 
  array (
    'is_secure' => false,
  ),
  'card' => 
  array (
    'is_secure' => false,
  ),
  'video' => 
  array (
    'is_secure' => false,
  ),
  'viewdocument' => 
  array (
    'is_secure' => false,
  ),
  'navfile' => 
  array (
    'is_secure' => false,
  ),
  'thumbnail' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
